monolog:
    channels:
        - gnews

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!gnews"]
            
            gnews:
                type: stream
                path: "%kernel.logs_dir%/gnews.log"
                level: debug
                channels: ["gnews"]
            
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event", "!gnews"]
            
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            
            gnews:
                type: stream
                path: "%kernel.logs_dir%/gnews.log"
                level: info
                channels: ["gnews"]
                formatter: monolog.formatter.json
            
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                channels: ["!event"]
            
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
