# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    gnews_api_key: '%env(GNEWS_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/Article/Entity/'
            - '../src/Infrastructure/Persistence/Doctrine/Entity/'
            - '../src/Kernel.php'

    # Domain repository interface binding
    App\Domain\Article\Repository\ArticleRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineArticleRepository

    # GNews API Client
    App\Infrastructure\ExternalApi\GNews\GNewsApiClient:
        arguments:
            $apiKey: '%gnews_api_key%'
            $logger: '@monolog.logger.gnews'

    # Fetch Articles Use Case with GNews logger
    App\Application\Article\UseCase\FetchArticlesUseCase:
        arguments:
            $logger: '@monolog.logger.gnews'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
